import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Logger } from "@/core/logger/app.logger";
import { dashboardKeys } from "@/features/dashboard/hooks/dashboard.keys";
import { devicesKeys } from "@/features/devices/hooks/devices.keys";
import { roomsKeys } from "@/features/rooms/hooks/rooms.keys";
import { clearMockHouseRequest } from "../api/dev.api";

/**
 * Removes the mock house (rooms + devices) previously generated by
 * useSeedMockHouse and refreshes every screen affected by the removal.
 */
export function useClearMockHouse() {
	const queryClient = useQueryClient();

	return useMutation({
		mutationFn: clearMockHouseRequest,
		onSuccess: (data) => {
			queryClient.invalidateQueries({ queryKey: devicesKeys.lists() });
			queryClient.invalidateQueries({ queryKey: dashboardKeys.overview() });
			queryClient.invalidateQueries({ queryKey: roomsKeys.lists() });
			toast.success(
				`Casa mock removida: ${data.devicesRemoved} dispositivos, ${data.roomsRemoved} ambientes.`,
			);
		},
		onError: (error: Error) => {
			Logger.error("Falha ao remover a casa mock", error);
			toast.error(error.message || "Não foi possível remover a casa mock.");
		},
	});
}
